#+TITLE:       summary of 2015
#+AUTHOR:      李海峰
#+EMAIL:       lihaifeng@hyphenlee.local
#+DATE:        2016-02-08 Mon
#+URI:         /blog/%y/%m/%d/summary-of-2015
#+KEYWORDS:    life
#+TAGS:        life
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: summary of 2015
* 概要
今年主要的任务就是记录，为此连运动和阅读都弱化了，最大的学习收益就是把
《幸福公开课》看完了，不过想要有实际的效益还是要靠之后不断的努力实践来
达成，今年最大的成功就是有坚持写日记，写每月的总结，每个月有设定计划以
及追踪计划，虽然计划完成都不是很好，至少有了一个开始，幸福公开课说了关
于计划的重要性，我尝试后深刻的感受到设定计划对幸福度的提升，也让自己的
生活更有条例，并且今年仍旧有坚持记录财务收支，虽然花钱还是很多，没有节
省的计划，但是后面就需要开始执行储蓄的计划了，所以记账还是有很大意义的。
* 工作
4月份换到做汽车导航的日企，在这家企业看到了很多大企业的流程，深刻感受
到日企对严谨，学会了很多，包括需求规划，代码提交、审核的流程，包括对
git对使用也更加熟练了，还学会用python写自动化测试，但是因为日企加班过
于严重，导致完全没有个人时间，而且流程过于繁杂，所以一直不适应，就不愿
意长期待下去。工作了5个月后又换到一家在线教育的国内民营企业，总的来说
公司的技术能力弱了很多，但是相对比较自由，自己进来的这段时间一直都在研
究webrtc的编译和使用，因为网络原因，webrtc一直无法按照官网所说的方式进
行下载和编译，源码是能下载下来但是依赖的库很大，一直无法完整的下载下来，
而且git不支持断点续传，很多时候下一半断了又要重新下载，所以公司之前一
直搞不定，我自己试了很长时间也没有办法，但是webrtc本身的源码是可以下载
下来的，所以我用cmake重新构建的编译系统，自己一个个的解决掉webrtc所有
的依赖，在android和ios以及mac上都编译出了需要的模块，然后webrtc的文档
一直不全，所有的使用方式都是通过看源代码来获得的，这段时间cmake的使用
功底提升了很多，看了大量webrtc的源码也学习到了很多C++编程和音视频处理
的算法，收益良多，后面还在ios下基于webrtc用oc混合C++的方式做了在线音视
频流的直播的软件，对ios开发也有了进一步深入对了解，后面公司的打算是依
旧基于webrtc实现mac版本的客户端。
* 生活爱好
** 坚持学吉他
有试着学《伯克利吉他教程》但是进度很慢，学会了指弹《风之诗》，学了点弹
唱，但是嗓子不好，很多歌都唱不了，还是以学指弹为主，在练琴上花的时间也
不多，也没有很系统的学，都是断断续续的，不过自己开心就好。
** 滑板
偶尔周末会玩玩滑板，出去刷刷街什么的，不过玩的还不是很熟练，也没练什么动作。
** 幸福公开课
今年总算把这个看完了，也感觉收益良多，不过还是要坚持实践，才能把好处都变现。
* 阅读
** 百年孤独
名字确实容易弄混，读完后只剩下深入骨髓的孤独和萧条 末尾要是加上红楼里
的这一段就是绝配了： 为官的，家业凋零；富贵的，金银散尽；有恩的，死里
逃生；无情的，分明报应。欠命的，命已还；欠泪的，泪已尽。冤冤相报实非轻，
分离聚合皆前定。欲知命短问前生，老来富贵也真侥幸。看破的，遁入空门；痴
迷的，枉送了性命。好一似食尽鸟投林，落了片白茫茫大地真干净！
** 哈利波特3
从去年年尾一直看到现在(4月5号）才看完，用kindle看查词很方便，生词已经
不多了，看起来很流畅，看到孤苦伶仃的哈利遇到的他的教父black，特别是
black最后给哈利的那封信让人感觉心里暖暖的，lupin也很给力，还有哈利穿越
时间赶走dementor的那段也写得很好
* 运动
** 跑步
nike＋达到1746km，今年跑步减少了，去年年终总结记录的跑步里数是1509，只
跑了237公里，一部分原因是在日企工作的时候加班严重，晚上常常10点多到家，
没有时间运动，还有就是为了控制自己的体重，就刻意减少运动量了。
** 体重控制
因为一直感觉自己太瘦了，所以今年有意识的增加自己的体重，成效还是很明显
的，年初大概只有60kg，年末达到67.4kg，称的方式是早上空腹且上完厕所后且
扣除衣物的重量，也就是自己一天当中最轻的时候的重量，所以平时去称的话会
有71kg多。

